apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  neutron:
    template:
      customServiceConfig: |
        [DEFAULT]
        dns_domain = openstackgate.local
        vlan_transparent = true
        service_plugins = qos,ovn-router-flavors-ha,trunk,segments,port_forwarding,log
        dhcp_agent_notification = false
        agent_down_time = 600
        router_distributed = true
        router_scheduler_driver = neutron.scheduler.l3_agent_scheduler.ChanceScheduler
        allow_automatic_l3agent_failover = true
        debug = true
        log_dir = /var/log/neutron

        [agent]
        report_interval = 300

        [database]
        max_retries = -1
        db_max_retries = -1

        [keystone_authtoken]
        region_name = regionOne
        memcache_use_advanced_pool = True
        auth_type = password

        [nova]
        region_name = regionOne
        endpoint_type = internal

        [oslo_messaging_notifications]
        driver = noop

        [oslo_middleware]
        enable_proxy_headers_parsing = true

        [oslo_policy]
        policy_file = /etc/neutron/policy.yaml

        [placement]
        region_name = regionOne

        [service_providers]
        service_provider=L3_ROUTER_NAT:user-defined:neutron.services.ovn_l3.service_providers.user_defined.UserDefined
        
        [ovs]
        igmp_snooping_enable = true
        
  
        [ml2]
        overlay_ip_version = 6
        type_drivers = geneve,vxlan,vlan,flat
        tenant_network_types = geneve,flat
        extension_drivers = qos,port_security,dns_domain_ports

        [ml2_type_flat]
        flat_networks = datacentre

        [ml2_type_geneve]
        vni_ranges = 1:65536
        max_header_size = 38

        [ml2_type_vlan]
        network_vlan_ranges = tenant:1000:2000

        [ml2_type_vxlan]
        vni_ranges = 1:65536
        vxlan_group = 224.0.0.1


  nova:
    template:
      schedulerServiceTemplate:
        customServiceConfig: |
          [filter_scheduler]
          enabled_filters = AggregateInstanceExtraSpecsFilter, AvailabilityZoneFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,DifferentHostFilter,SameHostFilter,AllHostsFilter,ServerGroupAffinityFilter,ServerGroupAntiAffinityFilter


